[project]
name = ""
version = ""
description = ""
authors = [
    {name = "takesi"},
]
dependencies = [
    "online-judge-tools==9.2.2",
    "lxml~=4.6",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
