#!/bin/bash -e

function usage() {
  echo "usage: atc {login,l,download,dl,d,test,t} ..."
  echo ""
  echo "command arguments:"
  echo ""
  echo "    login (l)                              login to atcoder"
  echo ""
  echo "    download (d, dl) contest               download sample cases"
  echo "            contest : contest name e.g. 'abc100'"
  echo "                      if you use '.' it will auto detect from path"
  echo ""
  echo "    test (t) task [samples]                test a task"
  echo "            task    : task name e.g. 'a'"
  echo "            samples : sample names e.g. '123' '1-4' all samples if not given"
}

base_url="https://atcoder.jp/"
cmd="./a.out"

case "$1" in
  "l" | "login")
    oj login ${base_url}
    ;;
  "d" | "dl" | "download")
    contest=$2
    if [ -z "${contest}" ]; then
      usage
      exit 1
    fi
    if [ "${contest}" == "." ]; then
      name=$(pwd)
      if [[ $name} =~ /([a-zA-Z0-9\-]+)$ ]]; then
        contest=${BASH_REMATCH[1]}
        echo "Extract contest ${contest} from path"
      fi
    fi
    tasks=$(atc-tasks ${contest})
    for task in ${tasks}
      do
      regexp="([a-z]),(.*)$"
      if [[ ${task} =~ $regexp ]]; then
        task=${BASH_REMATCH[1]}
        url=${BASH_REMATCH[2]}
        printf "[\e[34;1mDownloading ${task} samples\e[m]\n"
        oj dl -s -d . -f "${task}.%i.%e" ${url}
        for file in ${task}.[1-9].in
          do
          mv ${file} ${file/.in/}
        done
        for file in ${task}.[1-9].out
          do
          mv ${file} ${file/.out/.ans}
        done
        if [ ! -e "${task}.cpp" ]; then
          touch ${task}.cpp
        fi
      fi
    done
    ;;
  "t" | "test")
    task=$2
    samples=$3
    if [ -z "${task}" ]; then
      usage
      exit 1
    fi
    if [ ! -e "${cmd}" ]; then
      echo "No execution file ${cmd}"
      exit 1
    fi
    if [ -z "${samples}" ]; then
      samples=1-9
    fi
    for file in ${task}.[$samples]
      do
      printf "[\e[34;1m${file}\e[m]\n"
      ${cmd} < ${file}
      printf "[\e[35;1mans\e[m]\n"
      cat ${file}.ans
      echo ""
    done
    ;;
  *)
    usage
    ;;
esac
