#!/usr/bin/env python3

import sys

if len(sys.argv) < 2:
  exit()

file = open(sys.argv[1])
lines = file.readlines()

flag = False
for line in lines:
  if not flag:
    if line == '[ans]\n':
      flag = True
  else:
    print(line, end='')
